---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: test
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: frontend
  chart:
    repository: https://flagger.app/
    name: podinfo
    version: 2.2.0
  values:
    faults:
      error: false
    image:
      repository: chapod21/podinfo
      tag: dev-u1qjulwx
    backend: http://backend-podinfo:9898/echo
    canary:
      thresholds:
        latency: 100
      analysis:
        maxWeight: 5
        interval: 1m
        threshold: 2
        stepWeight: 1
      enabled: true
      helmtest:
        enabled: false
        url: http://flagger-helmtester-loadtester.kube-system
      istioIngress:
        enabled: true
        gateway: internal.istio-system.svc.cluster.local
        host: testing.flagger.store.aws.z8s.io
      loadtest:
        enabled: false
