apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: loadtester
  namespace: test
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:0.*
spec:
  releaseName: flagger-loadtester
  chart:
    repository: https://flagger.app/
    name: loadtester
    version: 0.4.1
  values:
    image:
      repository: weaveworks/flagger-loadtester
